// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingCart.Entities.Data;

#nullable disable

namespace ShoppingCart.API.Migrations
{
    [DbContext(typeof(ShoppingCartDatabaseContext))]
    [Migration("20220723135317_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShoppingCart.Entities.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("TimeUpdated")
                        .HasColumnType("datetime");

                    b.HasKey("CartId");

                    b.ToTable("Cart");

                    b.HasData(
                        new
                        {
                            CartId = 1,
                            CreatedBy = "User 1",
                            Status = 0,
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3379),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3408)
                        },
                        new
                        {
                            CartId = 2,
                            CreatedBy = "User 2",
                            Status = 0,
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3412),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3410)
                        },
                        new
                        {
                            CartId = 3,
                            CreatedBy = "User 3",
                            Status = 2,
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3415),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3413)
                        },
                        new
                        {
                            CartId = 4,
                            CreatedBy = "User 1",
                            Status = 1,
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3418),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3417)
                        },
                        new
                        {
                            CartId = 5,
                            CreatedBy = "User 1",
                            Status = 1,
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3421),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3420)
                        });
                });

            modelBuilder.Entity("ShoppingCart.Entities.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"), 1L, 1);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("TimeUpdated")
                        .HasColumnType("datetime");

                    b.HasKey("CartItemId", "CartId");

                    b.HasIndex("CartId");

                    b.ToTable("CartItem");

                    b.HasData(
                        new
                        {
                            CartItemId = 1,
                            CartId = 1,
                            Amount = 2m,
                            CreatedBy = "User 1",
                            Description = "CartItem 1 Description",
                            Name = "CartItem 1 Name",
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3529),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3532)
                        },
                        new
                        {
                            CartItemId = 2,
                            CartId = 1,
                            Amount = 2m,
                            CreatedBy = "User 1",
                            Description = "CartItem 2 Description",
                            Name = "CartItem 2 Name",
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3535),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3537)
                        },
                        new
                        {
                            CartItemId = 3,
                            CartId = 1,
                            Amount = 2m,
                            CreatedBy = "User 1",
                            Description = "CartItem 3 Description",
                            Name = "CartItem 3 Name",
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3539),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3540)
                        },
                        new
                        {
                            CartItemId = 4,
                            CartId = 1,
                            Amount = 2m,
                            CreatedBy = "User 1",
                            Description = "CartItem 4 Description",
                            Name = "CartItem 4 Name",
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3542),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3543)
                        },
                        new
                        {
                            CartItemId = 5,
                            CartId = 1,
                            Amount = 2m,
                            CreatedBy = "User 1",
                            Description = "CartItem 5 Description",
                            Name = "CartItem 5 Name",
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3545),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3547)
                        },
                        new
                        {
                            CartItemId = 1,
                            CartId = 2,
                            Amount = 2m,
                            CreatedBy = "User 1",
                            Description = "CartItem 1 Description",
                            Name = "CartItem 1 Name",
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3548),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3550)
                        },
                        new
                        {
                            CartItemId = 2,
                            CartId = 2,
                            Amount = 2m,
                            CreatedBy = "User 1",
                            Description = "CartItem 2 Description",
                            Name = "CartItem 2 Name",
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3551),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3553)
                        },
                        new
                        {
                            CartItemId = 3,
                            CartId = 2,
                            Amount = 2m,
                            CreatedBy = "User 1",
                            Description = "CartItem 3 Description",
                            Name = "CartItem 3 Name",
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3555),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3556)
                        },
                        new
                        {
                            CartItemId = 4,
                            CartId = 2,
                            Amount = 2m,
                            CreatedBy = "User 1",
                            Description = "CartItem 4 Description",
                            Name = "CartItem 4 Name",
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3558),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3560)
                        },
                        new
                        {
                            CartItemId = 5,
                            CartId = 2,
                            Amount = 2m,
                            CreatedBy = "User 1",
                            Description = "CartItem 5 Description",
                            Name = "CartItem 5 Name",
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3562),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3563)
                        },
                        new
                        {
                            CartItemId = 1,
                            CartId = 3,
                            Amount = 2m,
                            CreatedBy = "User 1",
                            Description = "CartItem 1 Description",
                            Name = "CartItem 1 Name",
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3566),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3567)
                        },
                        new
                        {
                            CartItemId = 2,
                            CartId = 3,
                            Amount = 2m,
                            CreatedBy = "User 1",
                            Description = "CartItem 2 Description",
                            Name = "CartItem 2 Name",
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3569),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3570)
                        },
                        new
                        {
                            CartItemId = 3,
                            CartId = 3,
                            Amount = 2m,
                            CreatedBy = "User 1",
                            Description = "CartItem 3 Description",
                            Name = "CartItem 3 Name",
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3572),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3573)
                        },
                        new
                        {
                            CartItemId = 4,
                            CartId = 3,
                            Amount = 2m,
                            CreatedBy = "User 1",
                            Description = "CartItem 4 Description",
                            Name = "CartItem 4 Name",
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3575),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3577)
                        },
                        new
                        {
                            CartItemId = 5,
                            CartId = 3,
                            Amount = 2m,
                            CreatedBy = "User 1",
                            Description = "CartItem 5 Description",
                            Name = "CartItem 5 Name",
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3578),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3580)
                        },
                        new
                        {
                            CartItemId = 1,
                            CartId = 4,
                            Amount = 2m,
                            CreatedBy = "User 1",
                            Description = "CartItem 1 Description",
                            Name = "CartItem 1 Name",
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3582),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3583)
                        },
                        new
                        {
                            CartItemId = 2,
                            CartId = 4,
                            Amount = 2m,
                            CreatedBy = "User 1",
                            Description = "CartItem 2 Description",
                            Name = "CartItem 2 Name",
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3585),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3586)
                        },
                        new
                        {
                            CartItemId = 3,
                            CartId = 4,
                            Amount = 2m,
                            CreatedBy = "User 1",
                            Description = "CartItem 3 Description",
                            Name = "CartItem 3 Name",
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3588),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3589)
                        },
                        new
                        {
                            CartItemId = 4,
                            CartId = 4,
                            Amount = 2m,
                            CreatedBy = "User 1",
                            Description = "CartItem 4 Description",
                            Name = "CartItem 4 Name",
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3591),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3592)
                        },
                        new
                        {
                            CartItemId = 5,
                            CartId = 4,
                            Amount = 2m,
                            CreatedBy = "User 1",
                            Description = "CartItem 5 Description",
                            Name = "CartItem 5 Name",
                            TimeCreated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3594),
                            TimeUpdated = new DateTime(2022, 7, 23, 15, 53, 16, 854, DateTimeKind.Local).AddTicks(3596)
                        });
                });

            modelBuilder.Entity("ShoppingCart.Entities.Models.CartItem", b =>
                {
                    b.HasOne("ShoppingCart.Entities.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CartItem_Cart");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("ShoppingCart.Entities.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
