// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingCart.Entities.Data;

#nullable disable

namespace ShoppingCart.API.Migrations
{
    [DbContext(typeof(ShoppingCartDatabaseContext))]
    partial class ShoppingCartDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShoppingCart.Entities.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("TimeUpdated")
                        .HasColumnType("datetime");

                    b.HasKey("CartId");

                    b.ToTable("Cart");

                    b.HasData(
                        new
                        {
                            CartId = 1,
                            CreatedBy = "User 1",
                            Status = 0,
                            TimeCreated = new DateTime(2022, 7, 18, 21, 14, 27, 608, DateTimeKind.Utc).AddTicks(24),
                            TimeUpdated = new DateTime(2022, 7, 18, 21, 14, 27, 608, DateTimeKind.Utc).AddTicks(26)
                        },
                        new
                        {
                            CartId = 2,
                            CreatedBy = "User 2",
                            Status = 0,
                            TimeCreated = new DateTime(2022, 7, 18, 21, 14, 27, 608, DateTimeKind.Utc).AddTicks(27),
                            TimeUpdated = new DateTime(2022, 7, 18, 21, 14, 27, 608, DateTimeKind.Utc).AddTicks(27)
                        },
                        new
                        {
                            CartId = 3,
                            CreatedBy = "User 3",
                            Status = 0,
                            TimeCreated = new DateTime(2022, 7, 18, 21, 14, 27, 608, DateTimeKind.Utc).AddTicks(28),
                            TimeUpdated = new DateTime(2022, 7, 18, 21, 14, 27, 608, DateTimeKind.Utc).AddTicks(28)
                        });
                });

            modelBuilder.Entity("ShoppingCart.Entities.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"), 1L, 1);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("TimeUpdated")
                        .HasColumnType("datetime");

                    b.HasKey("CartItemId", "CartId");

                    b.HasIndex("CartId");

                    b.ToTable("CartItem");

                    b.HasData(
                        new
                        {
                            CartItemId = 1,
                            CartId = 1,
                            Amount = 2m,
                            CreatedBy = "User 1",
                            Description = "CartItem 1 Description",
                            Name = "CartItem 1 Name",
                            TimeCreated = new DateTime(2022, 7, 18, 21, 14, 27, 608, DateTimeKind.Utc).AddTicks(158),
                            TimeUpdated = new DateTime(2022, 7, 18, 21, 14, 27, 608, DateTimeKind.Utc).AddTicks(158)
                        },
                        new
                        {
                            CartItemId = 2,
                            CartId = 1,
                            Amount = 2m,
                            CreatedBy = "User 1",
                            Description = "CartItem 2 Description",
                            Name = "CartItem 2 Name",
                            TimeCreated = new DateTime(2022, 7, 18, 21, 14, 27, 608, DateTimeKind.Utc).AddTicks(162),
                            TimeUpdated = new DateTime(2022, 7, 18, 21, 14, 27, 608, DateTimeKind.Utc).AddTicks(162)
                        });
                });

            modelBuilder.Entity("ShoppingCart.Entities.Models.CartItem", b =>
                {
                    b.HasOne("ShoppingCart.Entities.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CartItem_Cart");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("ShoppingCart.Entities.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
